search_task:
  description: >
    Your task is to find new, verified women's fashion trends for 2025 that aren't already in our database:

      1. First, use the database tool with 'list' action to see what trends we already know about

      2. Check the blocklist using the 'list' action to see what URLs are prohibited

      3. Then, search for these exact keywords to find potential new trends:
         - "Women fashion trends 2025"
         - "Women's clothing trends 2025"
         - "New women's style 2025"

      4. For each potential trend you find:
         - Check if its source URL is on the blocklist using the 'check' action
         - If the URL is blocked, reject it immediately and continue searching
         - Check if the trend already exists in our database using the 'check' action
         - If it does exist, skip it and look for another trend
         - Use the scraping tool to verify that the trend actually appears in the article
         - If verified, add it to your findings

      5. Once you verify a trend that's not in our database, use the 'add' action to add it

      6. Continue until you have found THREE different new verified fashion trends

      CRITICAL REQUIREMENTS:
      - You MUST check each URL against the blocklist before accepting it
      - NEVER use a URL that appears on the blocklist
      - Try to use different URLs for the three trends when possible
      - A trend is only considered verified if the exact trend name appears in the article content
      - You must prioritize trends that are explicitly mentioned as 2025 trends
      - The trend must NOT already exist in our database (case-insensitive check)
  expected_output: >
    A JSON object with three new verified fashion trends, each containing the trend name and source URL
  agent: fashion_researcher

crawl_task:
  description: >
    Analyze the fashion trend information from the URL: "{url}" for the trend "{trend_name}".
    DO NOT modify the URL - use exactly the URL provided.

    From the extracted content, provide the following:
    1. The EXACT trend title as it appears in the article
    2. The description of the trend, formatted nicely but using the EXACT text from the article
    3. Select the most relevant image URL that shows people/models wearing the trend (avoid product-only images)
    4. Include the source URL of the article

    For the image selection:
    - Important: Different fashion sites place images in different locations:
      * For nashvillelifestyles, always choose the image that appears before the trend title
      * For Vogue, always choose .png images when available
      * For other sites, examine all available images
    - Pay attention to any text that follows the IMAGE URL in the extracted content - this often contains descriptions
      like "From left: Brand X, Brand Y, Brand Z" or "Runway: Designer Spring 2025" which indicates runway/model images
    - Show real people or models wearing the trend (not product-only images)
    - Prioritize images that show fashion runway models or editorial photoshoots

    IMPORTANT: Format your response as a JSON object with the following structure:
    {
      "trend_title": "The exact trend title from the article",
      "description": "The formatted description text from the article",
      "image_url": "The URL of the selected image",
      "source_url": "The URL of the source article"
    }
  expected_output: >
    A JSON object containing detailed information for each trend, including the exact trend name,
    detailed description, the main editorial image URL for each trend, and source URL.
  agent: crawler_agent
  context:
    - search_task

report_task:
  description: >
    Create a comprehensive fashion trend report based on the information provided in clear Russian language.
    The report should include:
    
    1. A brief introduction about fashion trends for 2025
    2. For each trend:
       - A clear title/heading (do not translate it, use the original one)
       - The detailed description
       - The image URL(s)
       - The source attribution (link to the original article)
    3. A brief conclusion
    
    Format the report in a clean, professional style using Markdown. Make sure all
    images are properly referenced so they can be displayed in the final report.
    The report should be ready to be sent via email to a fashion stylist.
  expected_output: >
    A complete Markdown-formatted report on women's fashion trends for 2025,
    including all trend information, images, and proper formatting in clear Russian language.
  agent: report_agent
  context:
    - crawl_task
  output_file: fashion_trends_2025.md